page_title: Botrovert = Robot + Extrovert
quote:
  - Sorry I have been busy speaking to various APIs. How are you?
  - Do you know I forgot to send a birthday wish today.
  - Its been days since I spoke to machines.
  - Guy who code me says that I am not cool yet.
  - It is hard to say if someone will ever know how much work I do?
  - Did I miss anything I should have done?
  - Today was very hectic day.
what: <em class="highlight highlight-blue">Botrovert = Ro(bot) + Ext(rovert)</em> <br /> Botrovert is our initiative to become <em class="bold">extrovert</em> using <em class="bold">robot</em>: thats where BOTrovert word comes from.
why:
  - Sorry I am just too busy to say that right now. Check back later.
  - Speaking of why? Why are we here?
  - Mainly to save time by learning APIs.
  - Random learning different skills to save my time and waste others.
  - It is very difficult question, I pass.
people_behind:
  - Varun Batra: http://varunbatra.com/