quote: I hate to say but I don't like to talk to people! I talk to machines.
why: While my creator is busy in doing some magic, I am here to help him by making sure his friends think that he is with them.
more_why: Idea is to give his friends an illusion that they are being contacted by my creator.
who_is_creator: He is a <a href="http://varunbatra.com/">Web Application Consultant</a> and he spends most of his time by magic aka coding